= Synthesize a cluster

include::partial$synthesize-macros.adoc[]

TIP: "Synthesize" is the act of making a cluster managed by Project Syn

This how-to will show you how to synthesize a cluster.

== Prerequisites

* `cluster-admin` permissions on the cluster to synthesize.
* Write access in the Project Syn "Clusters" view on {portal-lieutenant-clusters}.
* Access to the {synfra-cluster}.
* The Syn tenant of the cluster to synthesize exists already.
If the tenant doesn't exist yet, see the documentation on xref:how-tos/create-tenant.adoc[creating a tenant].

== Procedure

. Create a new cluster in https://control.vshn.net/syn/lieutenantclusters/vshn-lieutenant-prod/_create[control.vshn.net].
See xref:explanation/synthesize.adoc#_creating_a_new_cluster_on_control_vshn_net[section "creating a new cluster on control.vshn.net"] of the "Synthesize a cluster" explanation for a more detailed breakdown of the form fields.

. Run Commodore to create a local checkout of the new cluster's configuration.
See the Project Syn https://syn.tools/syn/how-tos/compile-catalog.html["compile a catalog" how-to].
Use `\https://api.syn.vshn.net` as the value for `LIEUTENANT_URL`.
Skip the "Cleanup" of that tutorial step for now.

. Add any required initial configurations to your new cluster in `inventory/classes/<tenant-id>/<cluster-id>.yml`

. Run `commodore catalog compile --push <cluster-id>` to push the initial cluster catalog to https://git.vshn.net[git.vshn.net].

. Create any required secrets in Vault.
See the section describing how to <<_list_referenced_secrets,list referenced secrets>> to generate a list of all secrets referenced in the cluster catalog.

. Fetch the install URL from the {synfra-cluster}.
+
[source,bash]
----
export KUBECONFIG=/path/to/synfra.kubeconfig
export LIEUTENANT_TOKEN=$(kubectl config view -o jsonpath='{.users[?(@.name == "syn-synfra")].user.token}'  --raw)
export LIEUTENANT_AUTH="Authorization:Bearer ${LIEUTENANT_TOKEN}"

export INSTALL_URL=$(curl -H "${LIEUTENANT_AUTH}" "https://${LIEUTENANT_URL}/clusters/${CLUSTER_ID}" | jq -r ".installURL")
----
+
. Install Steward on the new cluster.
+
CAUTION: Make sure the `kubectl` command in this step is executed against the cluster to synthesize
+
[source,bash]
----
export KUBECONFIG=/path/to/new/cluster.kubeconfig
kubectl create -f "${INSTALL_URL}"
----
+
NOTE: See the documentation of the xref:explanation/bootstrap-token.adoc[bootstrap token and install URL] for a more detailed explanation, including instructions on how to reset the bootstrap token.
